version: '3.8'
services:
  api:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://user:pass@db:5432/app?schema=api_schema

  core:
    build:
      context: core
    env_file:
      - ./core/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://user:pass@db:5432/app
      - OPENAI_API_KEY=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
      - API_URL=http://api:3000
    command: python -u -m app.main

  
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app

  redis:
    image: redis:latest
    ports:
      - 6379:6379
