version: "3.8"
services:
  api:
    image: ghcr.io/fridonai/api:main
    restart: always
    ports:
      - "80:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://user:pass@db:5432/app?schema=api_schema
      - UPDATE_EMBEDDINGS_ON_BOOTSTRAP=1
      - ENABLE_UPDATE_EMBEDDINGS_CRON=1
    env_file:
      - .env

  core:
    image: ghcr.io/fridonai/core:main
    restart: always
    env_file:
      - ./core/.env
    command: python -u -m app.main

  db:
    build:
      dockerfile: pgvector.dockerfile
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
