version: "3.8"
services:
  api:
    image: ghcr.io/fridonai/api:main
    restart: always
    ports:
      - "80:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://user:pass@db:5432/app?schema=api_schema

  core:
    image: ghcr.io/fridonai/core:main
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://user:pass@db:5432/app?schema=core_schema
      - OPENAI_API_KEY=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
      - API_URL=http://api:3000
    command: python -u -m app.main

  db:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
