version: "3.8"
services:
  api:
    image: ghcr.io/fridonai/api:main
    restart: always
    ports:
      - "80:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://user:pass@db:5432/app?schema=api_schema
      - UPDATE_EMBEDDINGS_ON_BOOTSTRAP=1
      - ENABLE_UPDATE_EMBEDDINGS_CRON=1

  core:
    image: ghcr.io/fridonai/core:main
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://user:pass@db:5432/app?schema=core_schema
      - POSTGRES_DB_URL=postgresql://user:pass@db:5432/app
      - OPENAI_API_KEY=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
      - API_URL=http://api:3000
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_ENDPOINT=https://api.smith.langchain.com
      - LANGCHAIN_API_KEY=ls__69a4a95103294035bd82ad3aa61566f3
      - LANGCHAIN_PROJECT=fridon-ai
      - GPT_MODEL=gpt-4-0125-preview
      - BIRDEYE_API_KEY="9f0fc8d9eb0f42758e36ea3f71bec8d6"
      - PINECONE_API_KEY="2624d610-9ebc-43e6-95f1-81513475a096"
      # Todo: delete
      - POSTGRES_HOST=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app
      - POSTGRES_PORT=5432
    command: python -u -m app.main

  db:
    build:
      dockerfile: pgvector.dockerfile
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379
